---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/testimonials":
    get:
      summary: all testimonials
      tags:
      - Testimonials
      parameters:
      - name: page
        in: query
        description: Parameter used for paging
        schema:
          type: integer
      responses:
        '200':
          description: success status when getting all users (no token required)
    post:
      summary: creates a testimonial
      tags:
      - Testimonials
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: testimonial created
        '400':
          description: bad request status if not pass the required parameters or sends
            some invalid parameter
        '401':
          description: unauthorized status if you do not have a token or are a client
            user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                content:
                  type: string
              required:
              - name
              - content
  "/api/testimonials/{testimonial_id}":
    put:
      summary: update an existing testimonial
      tags:
      - Testimonials
      security:
      - bearer_auth: []
      parameters:
      - name: testimonial_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success status when testimonial updeted
        '401':
          description: unauthorized status if not have a token or are a client user
        '404':
          description: 'not found status if testimonial do not exist '
        '422':
          description: unprocessable entity status if not pass the required parameters
            or sends some invalid parameter
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                content:
                  type: string
              required:
              - name
              - content
    delete:
      summary: delete an existing testimonial
      tags:
      - Testimonials
      security:
      - bearer_auth: []
      parameters:
      - name: testimonial_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success status when testimonial deleted
        '401':
          description: unauthorized status if not have a token or are a client user
        '404':
          description: 'not found status if testimonial do not exist '
  "/api/categories":
    post:
      summary: Post a category
      tags:
      - Categories
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Category created
        '401':
          description: Unauthorized
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              required:
              - name
    get:
      summary: Get all categories
      tags:
      - Categories
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: List of categories
  "/api/categories/{id}":
    put:
      summary: Updates a category
      tags:
      - Categories
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Updated successfully
        '401':
          description: Unauthorized
        '422':
          description: Invalid request
        '404':
          description: Not found
    delete:
      summary: Delete a category
      tags:
      - Categories
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Not found
  "/api/organization/public":
    get:
      summary: Gets an Organization
      tags:
      - Organization
      parameters:
      - name: organization
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Organization found
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  adress:
                    type: string
                  phone:
                    type: integer
                  email:
                    type: string
                  welcome_text:
                    type: text
                  about_us_text:
                    type: text
                  facebook_url:
                    type: string
                  instagram_url:
                    type: string
                  linkedin_url:
                    type: string
                required:
                - name
                - email
                - welcome_text
    put:
      summary: Updates an Organization
      tags:
      - Organization
      security:
      - bearer_auth: {}
      parameters:
      - name: organization
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Organization updated
        '400':
          description: Parameter is missing or its value is empty
        '401':
          description: Unauthorized access.
servers:
- url: https://localhost:3000
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      name: Authorize
