---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths: {}
servers:
- url: http://localhost:3000
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      name: Authorize
