---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/organization/public":
    get:
      summary: Gets an Organization
      tags:
      - Organization
      parameters:
      - name: organization
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Organization found
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  adress:
                    type: string
                  phone:
                    type: integer
                  email:
                    type: string
                  welcome_text:
                    type: text
                  about_us_text:
                    type: text
                  facebook_url:
                    type: string
                  instagram_url:
                    type: string
                  linkedin_url:
                    type: string
                required:
                - name
                - email
                - welcome_text
    put:
      summary: Updates an Organization
      tags:
      - Organization
      security:
      - bearer_auth: {}
      parameters:
      - name: organization
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Organization updated
        '400':
          description: Parameter is missing or its value is empty
        '401':
          description: Unauthorized access.
servers:
- url: https://localhost:3000
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      name: Authorize
